name: PR-pipeline_opbase

on:
  pr_comment:
      types: [ created ]
      keyword: '^(?:\/)?compile*'
  pull_request_comment:
    types: [created]
    branches: [ '*' ]
    comments: [ '^(?:\/)?compile*' ]

env:
  org_name: "cann"
  repo_name: "opbase"
  MERGE_ID: ${{atomgit.event.pull_request.number}}
  TARGET_BRANCH: ${{atomgit.ref_name}}
  SOURCE_BRANCH: ${{atomgit.head_ref}}
  obs_path: "${{ vars.OBS_PATH }}/${{ env.MERGE_ID }}"
  obs_smoke_path: "${{ env.obs_path }}/presmoke/2"
  online: ${{ vars.APPLY_LABEL }}


stages:
  stage1:
    name: PreBuild
    jobs:
      JOB_image:
        name: Test_image
        steps:
          - name: revise_image
            identifier: revise_image
            uses: cann/.gitcode/actions/revise-img@master
            with:
              repo_name: "opbase"
              target_branch: ${{ env.TARGET_BRANCH }}
              repo_url: ${{ vars.CI_PATH }}
          -
            name: show_output
            run: |
              echo "image: ${{ steps.revise_image.outputs.Compile_Ascend_X86  }}"
        if: "${{ default() }}"
        runs-on: ["dedicate-hosted", "x64", "small"]
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/ubuntu20.04.05_x86:k8s_v1.1006
      JOB_pr:
        name: Test_get-pr
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
              token: ${{secrets.GIT_TOKEN}}
          -
            name: get_pr
            identifier: get_pr
            uses: cann/.gitcode/actions/get-pr@master
            with:
              workspace: ${{ steps.process_checkout.outputs.path }}
              target_branch: ${{ env.TARGET_BRANCH }}
              owner: ${{ env.org_name }}
              repo: ${{ env.repo_name }}
              pr_number: ${{ atomgit.event.pull_request.number }}
              git_token: ${{secrets.GIT_TOKEN}}
          -
            name: upload
            uses: obs-upload
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{secrets.AK}}
              secret-key: ${{secrets.SK}}
              artifact-path: |
                ${{ steps.process_checkout.outputs.path }}/pr_filelist.txt
                ${{ steps.process_checkout.outputs.path }}/pr_filelist_mod.txt
                ${{ steps.process_checkout.outputs.path }}/pr_filelist_precommit.txt
                ${{ steps.process_checkout.outputs.path }}/update_file_detail.txt
                ${{ steps.process_checkout.outputs.path }}/gitdiff.txt
              object-prefix: ${{ env.obs_path }}/
        runs-on:
        - default
      JOB_shell:
        name: Test_get-shell
        steps:
          -
            name: Checkout
            identifier: process_checkout
            uses: checkout
            with:
              ref: master
              token: ${{secrets.GIT_TOKEN}}
          -
            name: upload
            uses: obs-upload
            with:
              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
              bucket: "ascend-ci"
              access-key: ${{secrets.AK}}
              secret-key: ${{secrets.SK}}
              artifact-path: |
                ${{ steps.process_checkout.outputs.path }}/.gitcode/scripts/*
              object-prefix: ${{ env.obs_path }}/
        if: "${{ default() }}"
        runs-on:
        - default
      JOB_pre:
        name: Test_pre_pipeline
        steps:
          - name: pre_pipeline
            uses: cann/.gitcode/actions/pre-pipeline@master
            with:
              owner: ${{ env.org_name }}
              repo: ${{ env.repo_name }}
              pr_number: ${{ atomgit.event.pull_request.number }}
              token: ${{ secrets.GIT_TOKEN }}
              apply_label: ${{ vars.APPLY_LABEL }}
          - name: associate-pr-comment
            uses: associate-pr-comment
            if: env.online == 'true'
        runs-on: [dedicate-hosted, x64, small]
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/ubuntu20.04.05_x86:k8s_v1.1006
    pre:
    - type: auto
    fail-fast: true
  stage2:
    name: Compile
    jobs:
      JOB_codecheck:
        name: CodeCheck
        uses: cann/.gitcode/.gitcode/workflows/codecheck_action.yml@master
        with:
          precommit_image_version: ${{ jobs.JOB_image.outputs.precommit }}
          codecheck_image_version: ${{ jobs.JOB_image.outputs.codecheck }}
      JOB_x86_compile_ubuntu24:
        name: Compile_x86_ubuntu24
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'x86_compile_ubuntu24'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_X86_ubuntu24 }}
          arch: 'x64'
      JOB_arm_compile_ubuntu24:
        name: Compile_arm_ubuntu24
        uses: .gitcode/workflows/compile_action.yml
        with:
          task_name: 'arm_compile_ubuntu24'
          image_version: ${{ jobs.JOB_image.outputs.Compile_Ascend_ARM_ubuntu24 }}
          arch: 'arm64'
      JOB_staticcheck_md_check:
        name: staticcheck_md_check
        uses: .gitcode/workflows/staticcheck_action.yml
        with:
          check_type: 'md_check'
          image_version: ${{ jobs.JOB_image.outputs.staticcheck }}
    pre:
    - type: auto
    fail-fast: false
  stage3:
    name: UT
    jobs:
      JOB_api_check:
        name: API_Check
        steps:
          -
            name: api-check
            identifier: api-check
            uses: cann/.gitcode/actions/api-check@master
            with:
              org_name: ${{ env.org_name }}
              mode: check
              repo_name: ${{ env.repo_name }}
              merge_id: ${{ env.MERGE_ID }}
        if: env.TARGET_BRANCH == 'master'
        runs-on: [dedicate-hosted, x64, small]
        container:
          image: swr.cn-north-4.myhuaweicloud.com/ci_cann/${{ jobs.JOB_image.outputs.API_Check }}
      JOB_UT_Test:
        name: UT_Test
        uses: .gitcode/workflows/ut_action.yml
        with:
          ut_type: 'UT_Test'
          ut_package: 'coverage_*.info'
          image_version: ${{ jobs.JOB_image.outputs.UT_Test }}

post:
  jobs:
    job_post:
      name: Test_finish
      steps:
        -
          name: query_pipeline
          uses: cann/.gitcode/actions/query-pipeline@master
          with:
            owner: ${{ env.org_name }}
            repo: ${{ env.repo_name }}
            run_id: ${{atomgit. workflow_run_id}}
            token: ${{ secrets.GIT_TOKEN }}
            pr_number: ${{ env.MERGE_ID }}
            apply_label: ${{ vars.APPLY_LABEL }}
      runs-on: [dedicate-hosted, x64, small]
      container:
        image: swr.cn-north-4.myhuaweicloud.com/ci_cann/${{ jobs.JOB_image.outputs.codecheck }}
